const data = [
    {
        id: 0,
        name: "adidas Yeezy Boost 700 V2 Mauve",
        imgURL: "adidas-Yeezy-700-V2-Mauve-Product.jpg",
        price: 266,
        brand: "yeezy",
        ranking: 555,
        type: "sneaker",
        size: [8, 8.5, 9, 9.5, 10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 1,
        name: "adidas Yeezy Boost 350 V2 Light",
        imgURL: "adidas-Yeezy-Boost-350-V2-Light-Product.jpg",
        price: 234,
        brand: "yeezy",
        ranking: 655,
        type: "sneaker",
        size: [10, 11, 12, 13, 15, 18],
        sizeType: ["men", "woman"],
    },
    {
        id: 2,
        name: "adidas Yeezy Boost 350 V2 Mono Cinder",
        imgURL: "adidas-Yeezy-Boost-350-V2-Mono-Cinder.jpg",
        price: 218,
        brand: "yeezy",
        ranking: 789,
        type: "sneaker",
        size: [2, 3, 4, 5, 9, 10, 11],
        sizeType: ["men", "woman", "child"],
    },
    {
        id: 3,
        name: "adidas Yeezy Boost 700 MNVN",
        imgURL: "adidas-Yeezy-Boost-700-MNVN-Honey-Flux-Product.jpg",
        price: 212,
        brand: "yeezy",
        ranking: 745,
        type: "sneaker",
        size: [1, 2, 7, 10, 11],
        sizeType: ["men", "woman", "preshool"],
    },
    {
        id: 4,
        name: "adidas Yeezy Foam RNNR Ochre",
        imgURL: "adidas-Yeezy-Foam-RNNR-Ochre-Product.jpg",
        price: 159,
        brand: "yeezy",
        ranking: 109,
        type: "sneaker",
        size: [3, 4, 5, 6, 7, 8, 8.5, 9, 10, 11],
        sizeType: ["men", "woman", "preshool", "infant", "toddler"],
    },
    {
        id: 5,
        name: "adidas Yeezy Slide Glow Green",
        imgURL: "adidas-Yeezy-Slide-Glow-Green-Product.jpg",
        price: 94,
        brand: "yeezy",
        ranking: 492,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 6,
        name: "adidas Yeezy Slide Pure",
        imgURL: "adidas-Yeezy-Slide-Pure-Product.jpg",
        price: 124,
        brand: "yeezy",
        ranking: 725,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 7,
        name: "Jordan 1 Low Starfish",
        imgURL: "Air-Air-Jordan-1-Low-OG-Shattered-Backboard-Product.jpg",
        price: 193,
        brand: "jordan",
        ranking: 221,
        type: "sneaker",
        size: [8, 9, 9.5, 10, 11, 12],
        sizeType: ["men", "woman"],
    },
    {
        id: 8,
        name: "Jordan 1 Retro High OG Prototype ",
        imgURL: "Air-Jordan-1-High-OG-Pro-White-Blue-Black-Product.jpg",
        price: 190,
        brand: "jordan",
        ranking: 404,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 9,
        name: "Jordan 1 Retro High OG Seafoam (W)",
        imgURL: "Air-Jordan-1-High-OG-Seafoam-W-Product.jpg",
        price: 215,
        brand: "jordan",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["woman"],
    },
    {
        id: 10,
        name: "Jordan 1 Low Fragment x Travis Scott",
        imgURL: "Air-Jordan-1-Low-fragment-design-x-Travis-Scott-Product.jpg",
        price: 1031,
        brand: "jordan",
        ranking: 120,
        type: "sneaker",
        size: [10, 11, 12],
        sizeType: ["men", "woman"],
    },
    {
        id: 11,
        name: "Nike Dunk Low Retro White Black (2021)",
        imgURL: "Nike-Dunk-Low-Retro-White-Black-2021-Product.jpg",
        price: 247,
        brand: "nike",
        ranking: 676,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 12,
        name: "Nike Dunk Low SE Sail Multi-Camo",
        imgURL: "Nike-Dunk-Low-SE-Multi-Camo-Product.jpg",
        price: 164,
        brand: "nike",
        ranking: 371,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 13,
        name: "Nike Dunk Low Sail Light Bone (W)",
        imgURL: "Nike-Dunk-Low-Grey-Fog-Product.jpg",
        price: 181,
        brand: "nike",
        ranking: 333,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 14,
        name: "adidas ZX Fury ZX Pump",
        imgURL: "adidas ZX Fury ZX Pump.jpg",
        price: 95,
        brand: "reebok",
        ranking: 453,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 15,
        name: "Reebok Club C 85 White/Green",
        imgURL: "Reebok Club C 85 Bape White Contrast Stitch.jpg",
        price: 56,
        brand: "reebok",
        ranking: 489,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 16,
        name: "Reebok Club C Danielle Guizio",
        imgURL: "Reebok Club C Danielle Guizio.jpg",
        price: 199,
        brand: "reebok",
        ranking: 476,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 17,
        name: "Reebok Instapump Fury X GTX Citron",
        imgURL: "Reebok Instapump Fury X GTX Citron.jpg",
        price: 299,
        brand: "reebok",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 18,
        name: "New Balance 327 Angora (W)",
        imgURL: "New Balance 327 Angora (W).jpg",
        price: 102,
        brand: "newbalance",
        ranking: 456,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["woman"],
    },
    {
        id: 19,
        name: "New Balance 550 Aime Leon Dore White Green",
        imgURL: "New Balance 550 White Green.jpg",
        price: 215,
        brand: "newbalance",
        ranking: 147,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 20,
        name: "New Balance 550 White Purple",
        imgURL: "New Balance 550 White Purple.jpg",
        price: 125,
        brand: "newbalance",
        ranking: 478,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 21,
        name: "New Balance 550 White Red",
        imgURL: "New Balance 550 White Red.jpg",
        price: 155,
        brand: "newbalance",
        ranking: 469,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 22,
        name: "New Balance 990v3 Made In USA Version 3 Grey",
        imgURL: "New Balance 990v3 Made In USA Version 3 Grey.jpg",
        price: 200,
        brand: "newbalance",
        ranking: 156,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 23,
        name: "New Balance 2002R Salehe Bembury Water Be The Guide",
        imgURL: "New Balance 2002R Salehe Bembury Water Be The_yythk.jpg",
        price: 228,
        brand: "newbalance",
        ranking: 698,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 24,
        name: "A Bathing Ape Bapesta Grey Black",
        imgURL: "A Bathing Ape Bapesta Grey Black.jpg",
        price: 290,
        brand: "other",
        ranking: 478,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 25,
        name: "Converse Chuck Taylor All-Star 70 Hi Keith Haring Egret",
        imgURL: "Converse Chuck Taylor All-Star 70 Hi Keith Haring_y.jpg",
        price: 100,
        brand: "other",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 26,
        name: "Crocs Classic Clog Diplo Take a Walk on the Weird Side",
        imgURL: "Crocs Classic Clog Diplo Take a Walk on the_.jpg",
        price: 65,
        brand: "other",
        ranking: 791,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 27,
        name: "Crocs Classic Clog Justin Bieber with drew house 2 Lavender",
        imgURL: "Crocs Classic Clog Justin Bieber with drew house_yy.jpg",
        price: 99,
        brand: "other",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 28,
        name: "Crocs Classic Clog Lightning McQueen",
        imgURL: "Crocs Classic Clog Lightning McQueen.jpg",
        price: 150,
        brand: "other",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 29,
        name: "Fear of God Essentials Knit Pullover Hoodie Harvest",
        imgURL: "Fear of God Essentials Knit Pullover Hoodie Harvest.jpg",
        price: 107,
        brand: "fog",
        ranking: 465,
        type: "streetwear",
        size: ["L", "XL"],
        sizeType: ["men", "woman"],
    },
    {
        id: 30,
        name: "Fear of God Essentials Knit Pullover Hoodie Harvest",
        imgURL: "Fear of God Essentials Pull-Over Hoodie (SS21) Crea.jpg",
        price: 110,
        brand: "fog",
        ranking: 0,
        type: "streetwear",
        size: ["S", "M", "L", "XL"],
        sizeType: ["men", "woman"],
    },
    {
        id: 31,
        name: "Vlone Butterfly T-Shirt White",
        imgURL: "Juice-Wrld-x-Vlone-Butterfly-T-Shirt-White.jpg",
        price: 190,
        brand: "vlone",
        ranking: 0,
        type: "streetwear",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 32,
        name: "Travis Scott x McDonald's Crew T-shirt",
        imgURL: "Travis Scott x McDonald_s Crew T-Shirt Red.jpg",
        price: 37,
        brand: "mcdonal",
        ranking: 0,
        type: "streetwear",
        size: ["S", "M", "XXL"],
        sizeType: ["men", "woman"],
    },
    {
        id: 33,
        name: "Yeezy x Gap Hoodie Blue",
        imgURL: "Yeezy x Gap Hoodie Blue.jpg",
        price: 114,
        brand: "yeezy",
        ranking: 0,
        type: "streetwear",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 34,
        name: "Yeezy x Gap Hoodie Brown",
        imgURL: "Yeezy x Gap Hoodie Brown.jpg",
        price: 146,
        brand: "yeezy",
        ranking: 0,
        type: "streetwear",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 35,
        name: "Yeezy x Gap Hoodie Light Brown",
        imgURL: "Yeezy x Gap Hoodie Light Brown.jpg",
        price: 118,
        brand: "yeezy",
        ranking: 0,
        type: "streetwear",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 36,
        name: "Yeezy x Gap Hoodie Purple",
        imgURL: "Yeezy x Gap Hoodie Purple.jpg",
        price: 121,
        brand: "yeezy",
        ranking: 0,
        type: "streetwear",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 37,
        name: "Balenciaga Speed 2.0 Black White",
        imgURL: "Balenciaga Speed 2.0 Black White.jpg",
        price: 650,
        brand: "balenciaga",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 38,
        name: "Balenciaga Track Black",
        imgURL: "Balenciaga Track Black.jpg",
        price: 715,
        brand: "balenciaga",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 39,
        name: "Balenciaga Track White Orange",
        imgURL: "Balenciaga Track White Orange.jpg",
        price: 846,
        brand: "balenciaga",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 40,
        name: "Gucci Web Slide Sandal Black",
        imgURL: "Gucci Rubber Slides Red Green.jpg",
        price: 225,
        brand: "gucci",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 41,
        name: "Gucci Slides Bloom Supreme",
        imgURL: "Gucci Slides Bloom Supreme.jpg",
        price: 319,
        brand: "gucci",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 42,
        name: "Louis Vuitton Trainer Red White",
        imgURL: "Louis Vuitton Trainer Red White.jpg",
        price: 1300,
        brand: "lv",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 43,
        name: "Saint Laurent Court Classic SL_06 Low Distressed Cr",
        imgURL: "Saint Laurent Court Classic SL_06 Low Distressed Cr.jpg",
        price: 372,
        brand: "slp",
        ranking: 0,
        type: "sneaker",
        size: [10, 11],
        sizeType: ["men", "woman"],
    },
    {
        id: 44,
        name: "Hot Wheels x Tesla Cybertruck 1:10 Scale RC Car (2021 Version w/ Cyberquad)",
        imgURL: "Hot Wheels x Tesla Cybertruck 1_10 Scale RC.jpg",
        price: 91,
        brand: "hotwheel",
        ranking: 0,
        type: "collectibles",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 45,
        name: "Nintendo Switch (OLED) White",
        imgURL: "Nintendo Switch (OLED) White.jpg",
        price: 280,
        brand: "nintendo",
        ranking: 0,
        type: "collectibles",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 46,
        name: "Pokémon TCG 25th Anniversary Celebrations V Box Lan",
        imgURL: "Pokémon TCG 25th Anniversary Celebrations V Box Lan.jpg",
        price: 41,
        brand: "toys",
        ranking: 0,
        type: "collectibles",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 47,
        name: "Sony PS5 PlayStation 5 (US Plug) Blu-ray Edition_yy",
        imgURL: "Sony PS5 PlayStation 5 (US Plug) Blu-ray Edition_yy.jpg",
        price: 738,
        brand: "ps",
        ranking: 0,
        type: "collectibles",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 48,
        name: "Audemars Piguet Royal Oak 15300ST.OO.1220ST.03",
        imgURL: "Audemars Piguet Royal Oak 15300ST.OO.1220ST.03.jpg",
        price: 35000,
        brand: "ap",
        ranking: 0,
        type: "watch",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 49,
        name: "Audemars Piguet Royal Oak Offshore Chronograph 26470BA.OO.1000BA.01",
        imgURL: "Audemars Piguet Royal Oak Offshore Chronograph 26470BA.OO.1000BA.01.jpg",
        price: 32000,
        brand: "ap",
        ranking: 0,
        type: "watch",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 50,
        name: "Audemars-Piguet-Royal-Oak-26579CEOO1225CE01-Black-front",
        imgURL: "Audemars-Piguet-Royal-Oak-26579CEOO1225CE01-Black-front.jpg",
        price: 48000,
        brand: "vlone",
        ranking: 0,
        type: "watch",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 51,
        name: "Patek-Philippe-Nautilus-57121A-Blue-front",
        imgURL: "Patek-Philippe-Nautilus-57121A-Blue-front.jpg",
        price: 50000,
        brand: "patek",
        ranking: 0,
        type: "watch",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 52,
        name: "Rolex Oyster Perpetual GMT-Master II 126719BLRO",
        imgURL: "Rolex Oyster Perpetual GMT-Master II 126719BLRO.jpg",
        price: 37809,
        brand: "rolex",
        ranking: 0,
        type: "watch",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 53,
        name: "Rolex Sky-Dweller 326935",
        imgURL: "Rolex Sky-Dweller 326935.jpg",
        price: 34100,
        brand: "rolex",
        ranking: 0,
        type: "watch",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
    {
        id: 54,
        name: "Rolex-Daytona-116508-Green-front",
        imgURL: "Rolex-Daytona-116508-Green-front.jpg",
        price: 65500,
        brand: "rolex",
        ranking: 0,
        type: "watch",
        size: ["S", "M"],
        sizeType: ["men", "woman"],
    },
];

export default data;

// Brand
export const brand = [
    {
        key: "nike",
        title: "NIKE",
        type: "sneaker",
    },
    {
        key: "jordan",
        title: "AIR JORDAN",
        type: "sneaker",
    },
    {
        key: "yeezy",
        title: "YEEZY",
        type: "sneaker",
    },
    {
        key: "reebok",
        title: "REEBOK",
        type: "sneaker",
    },
    {
        key: "newbalance",
        title: "NEW BALANCE",
        type: "sneaker",
    },
    {
        key: "balenciaga",
        title: "BALENCIAGA",
        type: "sneaker",
    },
    {
        key: "gucci",
        title: "GUCCI",
        type: "sneaker",
    },
    {
        key: "lv",
        title: "LOUIS VUITTON",
        type: "sneaker",
    },
    {
        key: "other",
        title: "OTHER",
        type: "sneaker",
    },
    {
        key: "fog",
        title: "FEAR OF GOD",
        type: "streetwear",
    },
    {
        key: "vlone",
        title: "VLONE",
        type: "streetwear",
    },
    {
        key: "yeezy",
        title: "YEEZY",
        type: "streetwear",
    },
    {
        key: "hotwheel",
        title: "HOT WHEEL",
        type: "collectibles",
    },
    {
        key: "ps",
        title: "PLAY STATION",
        type: "collectibles",
    },
    {
        key: "nintendo",
        title: "NINTENDO",
        type: "collectibles",
    },
    {
        key: "toys",
        title: "OTHER",
        type: "collectibles",
    },
    {
        key: "rolex",
        title: "ROLEX",
        type: "watch",
    },
    {
        key: "ap",
        title: "Audemars Piguet",
        type: "watch",
    },
    {
        key: "patek",
        title: "Patek Philippe",
        type: "watch",
    },
];
